	<main class="container">
		<div class="slider">
			<?php foreach ($sliders as $slider): ?>
			<div><img src="<?= $slider['src'] ?>" alt="<?= $slider['alt'] ?>"></div>
			<?php endforeach; ?>
		</div> <!-- end of .slider -->
		<section class="intro">
			<h1><?= $config['name'] ?></h1>
			<img src="<?= $config['src'] ?>" alt="<?= $config['alt'] ?>" class="intro-img">
			<p><?= $config['content'] ?></p>
			
		</section>
		<section class="menu">
			<h2>Special menus</h2>
			<article>
				<h3>Meat menu</h3>
				<figure>
					<img src="img/meat-menu.jpg" alt="plate with red meat">
					<figcaption>17 $<br>
						<span>soft drinks and desert included</span>
						<span>+ taxes</span>
					</figcaption>
				</figure>
				<ul>
					<?php foreach($meals as $meal): ?>
					<?php if($meal['categoryName']=="Meat"):?>
					<li><i class="fas fa-star"></i><td><?= $meal['name'] ?> </td></li>
					<?php endif; ?> 
					 <?php endforeach; ?>
				</ul>
				<a href="menus.html" class="details"><img src="img/fork-knife.svg" alt="">See more</a>
			</article>
			<article>
				<h3>Fish menu</h3>
				<figure>
					<img src="img/fish-menu.jpg" alt="Plate with shrimps and rice">
					<figcaption>19 $<br>
						<span>soft drinks and desert included</span>
						<span>+ taxes</span>
					</figcaption>
				</figure>
				<ul>
					<?php foreach($meals as $meal): ?>
					<?php if($meal['categoryName']=="Fish"):?>
					<li><i class="fas fa-star"></i><td><?= $meal['name'] ?> </td></li>
					<?php endif; ?> 
					 <?php endforeach; ?>
				</ul>
				<a href="menus.html" class="details"><img src="img/fork-knife.svg" alt="">See more</a>
			</article>
			<article>
				<h3>Vegetarian menu</h3>
				<figure>
					<img src="img/vegetarian-menu.jpg" alt="colorfull vegetarian plate">
					<figcaption>18 $<br>
						<span>soft drinks and desert included</span>
						<span>+ taxes</span>
					</figcaption>
				</figure>
				<ul>
					<?php foreach($meals as $meal): ?>
					<?php if($meal['categoryName']=="Vegan"):?>
					<li><i class="fas fa-star"></i><td><?= $meal['name'] ?> </td></li>
					<?php endif; ?> 
					 <?php endforeach; ?>
				</ul>
				<a href="menus.html" class="details"><img src="img/fork-knife.svg" alt="">See more</a>
			</article>
		</section>
	</main>

	<!-- Charger la bibliothèque de base de jQuery -->
	<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
	<!-- Charger le script du plugin -->
	<script src="js/slick.min.js"></script>
	<!-- Indiquer sur quel élément de la page on applique le plugin -->
	<script>
		$(document).ready(function () {
			$('.slider').slick({
				dots: true
			});
		});
	</script>
