	<main class="container">
		<div class="slider">
			<div><img src="img/slider-01.jpg" alt="Table seen from the top with drinks and plates with food"></div>
			<div><img src="img/slider-02.jpg" alt="Zoom on a plate seen from the top and red chilli"></div>
			<div><img src="img/slider-03.jpg" alt="Table seen from the top with drinks and plates with food"></div>
		</div> <!-- end of .slider -->
		<section class="intro">
			<h1>Welcome to Freshly Restaurant</h1>
			<img src="img/location.jpg" alt="view of the main dining room" class="intro-img">
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptas sunt veritatis ipsam ipsa saepe unde possimus dicta accusantium nulla sequi praesentium commodi repudiandae, fugiat aperiam reiciendis impedit eius aspernatur at dolore placeat quae maxime laudantium optio sapiente! Architecto sequi totam qui illo doloribus nisi cupiditate perspiciatis culpa quam recusandae facere tempore necessitatibus expedita iusto facilis, quis nihil id dignissimos ex corporis minima sit. Eos deserunt maxime at animi obcaecati error rem numquam ullam vitae hic ducimus labore, in, iure nostrum!</p>
			<p>Soluta corporis est explicabo magni ducimus praesentium dignissimos hic laudantium accusantium maxime animi illum expedita sunt illo, eveniet voluptas reprehenderit quia, ipsam velit deserunt doloribus fugit iusto! Odit natus officia facere quae sunt eos unde repellat similique fugiat consectetur sint et qui, quod reiciendis perferendis. Corporis harum molestias doloribus, eaque est, quas. Amet doloribus aperiam voluptatem ad nemo minus voluptas ratione dolores in cumque dolore eius nostrum ipsa deleniti minima modi, officia odit temporibus velit excepturi, eligendi odio qui facere obcaecati.</p>
		</section>
		<section class="menu">
			<h2>Special menus</h2>
			<?php foreach($menus as $menu): ?>
			<article>
				<h3><?= $menu['title'] ?></h3>
				<figure>
					<img src="<?= $menu['src'] ?>" alt="<?= $menu['alt'] ?>">
					<figcaption><?= $menu['price'] ?> $<br>
						<span>soft drinks and desert included</span>
						<span>+ taxes</span>
					</figcaption>
				</figure>
				<ul>
					<li><i class="fas fa-star"></i>Lorem ipsum dolor sit.</li>
					<li><i class="fas fa-star"></i>Dolorem est fuga possimus.</li>
					<li><i class="fas fa-star"></i>Iste aperiam facere reprerit.</li>
					<li><i class="fas fa-star"></i>Amet consectur aperiam iusto.</li>
					<li><i class="fas fa-star"></i>Ipsa autem accusam ducimus.</li>
				</ul>
				<a href="menus.html" class="details"><img src="img/fork-knife.svg" alt="">See more</a>
			</article>
			<?php endforeach; ?>
		</section>
	</main>

	<!-- Charger la bibliothèque de base de jQuery -->
	<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
	<!-- Charger le script du plugin -->
	<script src="js/slick.min.js"></script>
	<!-- Indiquer sur quel élément de la page on applique le plugin -->
	<script>
		$(document).ready(function () {
			$('.slider').slick({
				dots: true
			});
		});
	</script>
