		<main class="container mixitup">
		<h1>Details of our menus</h1>
		<p class="select">Choose your main course according to your menu!</p>
		<div class="filter">
			<button data-filter="all">All</button>
<!--			faire une boucle
-->			<button data-filter=".meat">Meat</button>
			<button data-filter=".vegan">Vegan</button>
			<button data-filter=".fish">Fish</button>
		</div> <!-- end of .filter -->
		<div class="choice">
			<div class="mix fish">
				<?php foreach($meals as $meal): ?>
				<?php if($meal['categoryName']=="Fish"):?>
				<figure>
					<img src="<?= $meal['src'] ?>" alt="<?= $meal['alt'] ?>">
					<figcaption><img src="img/fork-knife.svg" alt="">
						<h3><?= $meal['name'] ?></h3>
					</figcaption>
				</figure>
				<?php endif; ?> 
				<?php endforeach; ?>
			</div>
			<div class="mix vegan">
				<?php foreach($meals as $meal): ?>
				<?php if($meal['categoryName']=="Vegan"):?>
				<figure>
					<img src="<?= $meal['src'] ?>" alt="<?= $meal['alt'] ?>">
					<figcaption><img src="img/fork-knife.svg" alt="">
						<h3><?= $meal['name'] ?></h3>
					</figcaption>
				</figure>
				<?php endif; ?> 
				<?php endforeach; ?>
			</div>
			<div class="mix meat">
				<?php foreach($meals as $meal): ?>
				<?php if($meal['categoryName']=="Meat"):?>
				<figure>
					<img src="<?= $meal['src'] ?>" alt="<?= $meal['alt'] ?>">
					<figcaption><img src="img/fork-knife.svg" alt="">
						<h3><?= $meal['name'] ?></h3>
					</figcaption>
				</figure>
				<?php endif; ?> 
				<?php endforeach; ?>
			</div>
			
			
		</div> <!-- end of .choice -->
		<article>
			<h2>Deserts</h2>
			<p class="select">Here are the deserts you can choose to finish your meal (included in your menu).</p>
			<div class="choice">
				<?php foreach($meals as $meal): ?>
				<?php if($meal['categoryName']=="Dessert"):?>
				<figure>
					<img src="<?= $meal['src'] ?>" alt="<?= $meal['alt'] ?>">
					<figcaption><img src="img/fork-knife.svg" alt="">
						<h3><?= $meal['name'] ?></h3>
					</figcaption>
				</figure>
				<?php endif; ?> 
				<?php endforeach; ?>
			</div> <!-- end of .choice -->
		</article>
		<article>
			<h2>Cocktails</h2>
			<p class="select">Soft drinkgs are included, but if you want you can order one of our excellent cocktails (not included in the menu).</p>
			<div class="choice">
				<?php foreach($meals as $meal): ?>
				<?php if($meal['categoryName']=="Cocktail"):?>
				<figure>
					<img src="<?= $meal['src'] ?>" alt="<?= $meal['alt'] ?>">
					<figcaption><img src="img/fork-knife.svg" alt="">
						<h3><?= $meal['name'] ?></h3>
					</figcaption>
				</figure>
				<?php endif; ?> 
				<?php endforeach; ?>
			</div> <!-- end of .choice -->
		</article>
	</main>
	
	<!-- Charger la bibliothèque de base de jQuery -->
	<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
	<!-- Charger le script du plugin -->
	<script src="js/mixitup.min.js"></script>
	<!-- Indiquer sur quel élément de la page on applique le plugin -->
	<script>
		var mixer = mixitup(".mixitup");
	</script>
</body>

</html>