<main>
    
    	<h1>Tableau de bord</h1>
    	
    <p>nombre de réservations en attente BONUS</p> 
    <p>nombre plats en bdd BONUS</p> 


<nav class="dashboard">
    <a href="index.php?page=category">Gestions des catégories de plats</a>
    <a href="index.php?page=meal">Gestions des plats</a>
    <a href="index.php?page=gestionMenu">Gestions des menus</a>
    <a href="#">Gestion du slider</a>
    <a href="#">Gestion des horaires</a>
    <a href="#">Gestion des réservations</a>
    <a href="#">page d'accueil</a>
    <a href="#">Coordonnées</a>
</nav>



</main>
